name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 변경사항이 생길 때 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Node.js 버전 설정

      - name: Install dependencies
        run: npm install # npm 또는 yarn으로 프로젝트 의존성 설치

      - name: Build project
        run: npm run build # 프로젝트 빌드 (예: React, Vue)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist # 빌드 결과물이 있는 디렉토리
